dataset:
  name: ces
  year: 24
  identity_col: caseid
  raw_data_path: ces/raw_data/merged_recontact_2024.dta
  codebook_path: ces/codebook.jsonl
  all_responses_path: ces/data/ces_responses.csv
  user_split_path: ces/data/user_split.json

region:
  column: region
  mapping:
    A: Northeast
    B: Midwest
    C: South
    D: West

demographics:
  columns:
    age: birthyr
    sex: gender4
    education: educ
    party: pid3
    ideology: ideo5
    income: faminc_new
    religion: religpew
    race: race

splits:
  id_col: caseid
  region_split: true
  in_distribution_region: South
  out_of_distribution_region: West
  val_size: 0.2
  seed: 42

questions:
  columns:
    - 327a
    - 327b
    - 327d
    - 330a
    - 330b
    - 330c
    - 331a
    - 331b
    - 331d
    - 332a
    - 332b
    - 332c
    - 332d
    - 332e
    - 332f
    - 332g
    - 333a
    - 333b
    - 333c
    - 333d
    - 334a
    - 334b
    - 334c
    - 334d
    - 334e
    - 334f
    - 334g
    - 334h
    - 355a
    - 355e