dataset:
  name: opinionqa
  identity_col: caseid
  raw_data_path: opinionqa/raw_data
  codebook_path: opinionqa/codebook.jsonl
  all_responses_path: opinionqa/data/opinionqa_responses.csv
  user_split_path: opinionqa/data/user_split.json
  all_question_keys_path: opinionqa/opinionqa_question_keys.json
  
region:
  column: F_CREGION
  mapping:
    A: Midwest
    B: Northeast
    C: South
    D: West

demographics:
  columns:
    age: F_AGECAT
    sex: F_SEX
    education: F_EDUCCAT2
    party: F_PARTY_FINAL
    ideology: F_IDEO
    income: F_INCOME
    religion: F_RELIG
    race: F_RACETHNMOD

splits:
  id_col: caseid
  region_split: true
  in_distribution_region: South
  out_of_distribution_region: West
  val_size: 0.2
  seed: 42

questions:
  columns:
    - FAMSURV2Wc_W50
    - FAMSURV1_W50
    - BILLION_W92
    - INEQ1_W54
    - USEXCEPT_W92
    - PROG_RNEED_W92
    - FAMSURV2Mc_W50
    - ECON1_W54
    - GOVPRIORITYd_W54
    - WHADVANT_W92
    - ECON4_b_W54
    - FREECOLL_W92
    - GOVPRIORITYc_W54
    - ELECT_CONF3_PRVFR_W92
    - FAMSURV6_W50
    - SATLIFEc_W50
    - CANDEXP_W92
    - ELECT_CONF3_PRVSUP_W92
    - GOVPRIORITYf_W54
    - FIN_SIT_W54
    - REPRSNTREP_W92
    - UNIMMIGCOMM_W92
    - POLINTOL2_a_W92
    - ECON4_a_W54
    - GOVPRIORITYb_W54
    - RACESURV52MOD_W92
    - GODMORALIMP_W92
    - ELECT_IMPT3_PRVFR_W92
    - REPRSNTDEM_W92
    - SOCIETY_TRANS_W92