dataset:
  name: twin
  identity_col: caseid
  raw_data_path: twin/raw_data/Twin-2K-500
  codebook_path: twin/codebook.jsonl
  all_responses_path: twin/data/twin_responses.csv
  user_split_path: twin/data/user_split.json


region:
  column: BLOCK0QID11_W1
  mapping:
    A: Northeast
    B: Midwest
    C: South
    D: West
    E: Pacific

demographics:
  columns:
    age: BLOCK0QID13_W1
    sex: BLOCK0QID12_W1
    education: BLOCK0QID14_W1
    party: BLOCK0QID20_W1
    ideology: BLOCK0QID22_W1
    income: BLOCK0QID21_W1
    religion: BLOCK0QID18_W1
    race: BLOCK0QID15_W1

splits:
  id_col: caseid
  region_split: true
  in_distribution_region: South
  out_of_distribution_region: West
  val_size: 0.2
  seed: 42


questions:
  columns:
    - BLOCK30QID9_1_W1
    - BLOCK30QID9_2_W1
    - BLOCK30QID9_3_W1
    - BLOCK30QID9_4_W1
    - BLOCK30QID9_5_W1
    - BLOCK30QID9_6_W1
    - BLOCK30QID9_7_W1
    - BLOCK30QID9_8_W1
    - BLOCK30QID9_9_W1
    - BLOCK30QID9_10_W1
    - BLOCK30QID9_11_W1
    - BLOCK30QID9_12_W1
    - BLOCK30QID9_13_W1
    - BLOCK30QID9_14_W1
    - BLOCK30QID9_15_W1
    - BLOCK30QID9_16_W1
    - BLOCK30QID9_17_W1
    - BLOCK30QID9_18_W1
    - BLOCK30QID9_19_W1
    - BLOCK30QID9_20_W1
    - BLOCK30QID9_21_W1
    - BLOCK30QID9_22_W1
    - BLOCK30QID9_23_W1
    - BLOCK30QID9_24_W1
    - BLOCK30QID9_25_W1
    - BLOCK30QID9_26_W1
    - BLOCK30QID9_27_W1
    - BLOCK30QID9_28_W1
    - BLOCK30QID9_29_W1
    - BLOCK30QID9_30_W1
    - BLOCK30QID9_31_W1
    - BLOCK30QID9_32_W1
    - BLOCK30QID9_33_W1
    - BLOCK30QID9_34_W1
    - BLOCK30QID9_35_W1
    - BLOCK30QID9_36_W1
    - BLOCK30QID9_37_W1
    - BLOCK30QID9_38_W1
    - BLOCK30QID9_39_W1
    - BLOCK30QID9_40_W1