# config.yaml
data:
  base_dir:  dataset/opinionqa/data
  id_dist: South
  ood_dist: West
  codebook_path: dataset/opinionqa/codebook.jsonl
  demo_cols: ['F_AGECAT', 'F_SEX', 'F_EDUCCAT2', 'F_PARTY_FINAL', 'F_IDEO', 'F_INCOME', 'F_RELIG', 'F_RACETHNMOD']
  question_cols: ['FAMSURV2Wc_W50', 'FAMSURV1_W50', 'BILLION_W92', 'INEQ1_W54', 'USEXCEPT_W92', 'PROG_RNEED_W92', 'FAMSURV2Mc_W50', 'ECON1_W54', 'GOVPRIORITYd_W54', 'WHADVANT_W92', 'ECON4_b_W54', 'FREECOLL_W92', 'GOVPRIORITYc_W54', 'ELECT_CONF3_PRVFR_W92', 'FAMSURV6_W50', 'SATLIFEc_W50', 'CANDEXP_W92', 'ELECT_CONF3_PRVSUP_W92', 'GOVPRIORITYf_W54', 'FIN_SIT_W54', 'REPRSNTREP_W92', 'UNIMMIGCOMM_W92', 'POLINTOL2_a_W92', 'ECON4_a_W54', 'GOVPRIORITYb_W54', 'RACESURV52MOD_W92', 'GODMORALIMP_W92', 'ELECT_IMPT3_PRVFR_W92', 'REPRSNTDEM_W92', 'SOCIETY_TRANS_W92']

split:
  path: dataset/opinionqa/data/user_split.json 
  mode: by_user       # ignored if path is set
  mask_ratio: 0.5

model:
  hidden: 64         
  layers: 2
  dropout: 0.10

optim:
  lr: 0.002
  weight_decay: 0.0001

train:
  epochs: 500
  batch_size: 2048
  seed: 42
  device: cuda        # auto | cpu | cuda

checkpoint:
  ckpt_dir: checkpoints/gnn
  ckpt_prefix: gnn_opinionqa_South_West

logs:
  log_dir: logs/gnn