# config.yaml
data:
  base_dir:  dataset/twin/data
  id_dist: South
  ood_dist: West
  codebook_path: dataset/twin/codebook.jsonl
  demo_cols: ['BLOCK0QID13_W1', 'BLOCK0QID12_W1', 'BLOCK0QID14_W1', 'BLOCK0QID20_W1', 'BLOCK0QID22_W1', 'BLOCK0QID21_W1', 'BLOCK0QID18_W1', 'BLOCK0QID15_W1']
  question_cols: ['BLOCK30QID9_18_W1', 'BLOCK30QID9_6_W1', 'BLOCK30QID9_23_W1', 'BLOCK30QID9_29_W1', 'BLOCK30QID9_19_W1', 'BLOCK30QID9_26_W1', 'BLOCK30QID9_37_W1', 'BLOCK30QID9_38_W1', 'BLOCK30QID9_32_W1', 'BLOCK30QID9_35_W1', 'BLOCK30QID9_17_W1', 'BLOCK30QID9_24_W1', 'BLOCK30QID9_39_W1', 'BLOCK30QID9_15_W1', 'BLOCK30QID9_9_W1', 'BLOCK30QID9_4_W1', 'BLOCK30QID9_13_W1', 'BLOCK30QID9_22_W1', 'BLOCK30QID9_34_W1', 'BLOCK30QID9_27_W1', 'BLOCK30QID9_10_W1', 'BLOCK30QID9_36_W1', 'BLOCK30QID9_2_W1', 'BLOCK30QID9_12_W1', 'BLOCK30QID9_1_W1', 'BLOCK30QID9_3_W1', 'BLOCK30QID9_20_W1', 'BLOCK30QID9_5_W1', 'BLOCK30QID9_25_W1', 'BLOCK30QID9_21_W1', 'BLOCK30QID9_33_W1', 'BLOCK30QID9_30_W1', 'BLOCK30QID9_7_W1', 'BLOCK30QID9_11_W1', 'BLOCK30QID9_28_W1', 'BLOCK30QID9_14_W1', 'BLOCK30QID9_40_W1', 'BLOCK30QID9_31_W1', 'BLOCK30QID9_16_W1', 'BLOCK30QID9_8_W1']
  
split:
  path: dataset/twin/data/user_split.json   # or .csv
  mode: by_user       # ignored if path is set
  mask_ratio: 0.5

model:
  hidden: 64         
  layers: 2
  dropout: 0.5

optim:
  lr: 0.001
  weight_decay: 0.005

train:
  epochs: 100
  batch_size: 2048
  seed: 42
  device: cuda        # auto | cpu | cuda

checkpoint:
  ckpt_dir: checkpoints/gnn
  ckpt_prefix: gnn_twin_South_West

logs:
  log_dir: logs/gnn